[package]
name = "asset-archive"
version = "0.1.0"
edition = "2021"

[dependencies]
bincode = "1.3"
byteorder = "1.4"
bzip2 = "0.4"
flate2 = "1.0"
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0"

[dev-dependencies]
rand = "0.8"
